### ISSUE TITLE
Some error when running

### ISSUE THREAD

**Issue by SengHongLEE** [MiladShafiee/DeepTransition#1]
Hey there, i clone the repository and setup an environment based on the readme.md, but i got this error. Thanks in advanced for solving.
![image](https://github.com/MiladShafiee/DeepTransition/assets/109339930/bbe02cab-70fd-4f51-a6f5-b714d79bc295)

**Comment by MiladShafiee** [comment]
Hello Seng-Hong, I guess it should be the problem of Isaac-Gym version, What's the version that you have currently installed?

**Comment by SengHongLEE** [comment]
> Hello Seng-Hong, I guess it should be the problem of Isaac-Gym version, What's the version that you have currently installed?

I install Isaac-Gym Preview 4 from the provided link. Could you please provide the Isaac-Gym Preview 3 you mentioned in the readme? I'm unable to get it from NVIDIA official.

**Comment by MiladShafiee** [comment]
I realized that we changed one line in our isaac-gym code, so by changing the terrain_utils.py in `isaacgym/python/isaacgym` it should work with Isaac Gym Preview 3/4:

change line 360: `self.height_field_raw = np.zeros((self.width, self.length), dtype=np.int16)` to `self.height_field_raw = np.zeros((self.length, self.width), dtype=np.int16)`.

@SengHongLEE Please let me know if it works.
