### ISSUE TITLE
How does the Emergence of Gait Transitions appear?

### ISSUE THREAD

**Issue by XanderWangXY** [MiladShafiee/DeepTransition#3]
Hello, I have been interested in CPG recently. Recently I tried your code, but I couldn't see the training process about gait transition. I see that in the original paper, the training process is divided into flat terrain and Gap Crossing, but I can not find the relevant part of the code. Looking forward to your early reply!

**Comment by MiladShafiee** [comment]
Hi @XanderWangXY. There is not any part of the code that wants to force the transition, the transition is emergent behavior that is learnt during the training autonomously.
